// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/17/2025, 10:01:03 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/sumitkumarpandit/codebase/misc/SumitKPandit.github.io/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sumitkumarpandit/codebase/misc/SumitKPandit.github.io/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sumitkumarpandit/codebase/misc/SumitKPandit.github.io/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sumitkumarpandit/codebase/misc/SumitKPandit.github.io/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sumitkumarpandit/codebase/misc/SumitKPandit.github.io/plugins/**/*.{js,ts,mjs}","/Users/sumitkumarpandit/codebase/misc/SumitKPandit.github.io/composables/**/*.{js,ts,mjs}","/Users/sumitkumarpandit/codebase/misc/SumitKPandit.github.io/utils/**/*.{js,ts,mjs}","/Users/sumitkumarpandit/codebase/misc/SumitKPandit.github.io/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sumitkumarpandit/codebase/misc/SumitKPandit.github.io/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/sumitkumarpandit/codebase/misc/SumitKPandit.github.io/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/sumitkumarpandit/codebase/misc/SumitKPandit.github.io/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["17"] = "/Users/sumitkumarpandit/codebase/misc/SumitKPandit.github.io/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;